import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "src_17_display_values_2.json"
OUTPUT = ROOT / "trans_17.json"
NEWTERMS = ROOT / "newterms_17.txt"

NEW_TERM_NOTES = ""


TRANSLATIONS = {
    "Double Helixes Intertwined": "双螺旋交织",
    "Falling Somewhere": "坠向某处",
    "First Contact": "初次接触",
    "Square Cube Law": "平方—立方定律",
    "Starchaser": "逐星者",
    "Twinkling": "闪烁",
    "Visual Object": "视觉对象",
    "Whole Lotta Lonely": "无尽孤独",
    "Yearning": "渴望",
    "AREA": "面积",
    "BUILD FROM DISTANCE": "根据距离构造",
    "DIFFERENT SHAPES": "不同形状",
    "Grouping Symbols": "分组符号",
    "HAS ENDHAS STORE DATA": "HAS 与 ENDHAS 存储数据",
    "HAS ENDHAS": "HAS 与 ENDHAS",
    "LINESEG": "线段",
    "PERIMETER": "周长",
    "POINT COMPOSITION": "点的构成",
    "POINT LABEL": "点的标签",
    "POINT": "点",
    "PYTHAGOREAN THEOREM": "勾股定理",
    "SHAPE": "形状",
    "SOLVE SHAPE CORNER": "求形状顶点",
    "Shapes": "形状",
    "WHICH POINTS MAKE WHICH LINE": "哪些点组成哪条线",
    "MEGA MULTI-PART ANS": "超大型多段答案",
    "MULTI-PART ANS": "多段答案",
    "Multi-Part Answers": "多段答案",
    "MAKE SHAPE": "构造形状",
    "MAKE TEST": "构造测试",
    "MAKE": "构造",
    "MULTI-SHAPE CONSTRUCTION": "多形状构造",
    "MOVE 3D SHAPE": "移动三维形状",
    "MOVE INFORMATION": "移动信息",
    "MOVE POINT TO CONTAINER": "将点移入容器",
    "DUMMY MESSAGE 2": "占位讯息 2",
    "LIST SIGNALS": "列出信号",
    "METEOR MAKE MESSAGE": "陨石生成讯息",
    "METEOR": "陨石",
    "Message": "讯息",
    "RECOGNIZE EARLY MESSAGE": "识别早期讯息",
    "RETURN METEOR": "返回陨石",
    "Meteor Signals": "陨石信号",
    "TOTAL TRANSMISSION COUNT": "传输总数",
    "WHICH SIGNAL AGAIN": "再次辨认信号",
    "Base-8": "八进制",
    "DESCENDING SPACES": "空格递减",
    "DOUBLE SPACE CLARIFY": "说明双空格",
    "Defining Space Gaps": "定义空格间距",
    "Format Numbers": "数字格式",
    "Advanced Arithmetic": "进阶算术",
    "CHAIN ADDITION": "连加运算",
    "DIVISION VICTORY LAP": "除法收官",
    "EQUALS NOT COMPUTE": "等号不表示计算",
    "Equal Expressions": "等值表达式",
    "FLOAT GRAND FINALE": "浮点数终章",
    "FLOAT": "浮点数",
    "MULTIPLY ADD": "乘法与加法",
    "Multiplication to 2 Digits": "两位数乘法",
    "OPERATION PARTY": "运算大集合",
    "Math Operations": "数学运算",
    "SUBTRACTION FLOATS": "浮点数减法",
    "Plot Horizontal Movement": "绘制水平移动",
    "Plot a Line": "绘制直线",
    "WITH SPACE": "带空格",
    "3 POINT PLOTS": "三点绘图",
    "ANS YET AGAIN": "答案再次登场",
    "ASSOCIATE VARIABLES": "关联变量",
    "CLARIFY ANS": "进一步说明答案",
    "CLARIFY VAR": "进一步说明变量",
    "FUNCTION WARMUP": "函数热身",
    "Functions": "函数",
    "PLOTS SPELLED OUT": "完整写出绘图",
    "PLOTS": "绘图",
    "VAR NUM DOES NOT MATTER": "变量编号无关紧要",
    "EASY QUADRATIC": "简单二次式",
    "EXPONENT BASE TOUGH": "棘手的指数底数",
    "Exponents": "指数",
    "Quadratic Curve": "二次曲线",
    "Solve for Exponent": "求指数",
    "UNNECESSARY INFO": "多余信息",
    "AND CLARIFY": "进一步说明“与”",
    "BIGGER SMALLER": "大与小",
    "CONTEXTLESS THEREFORE": "无上下文的“所以”",
    "GREATER THAN": "大于",
    "GREATER, LESSER, OR EQUALS": "大于、小于或等于",
    "Geometry Logic": "几何逻辑",
    "IF": "如果",
    "LESS THAN CLARIFY": "进一步说明“小于”",
    "LOGICAL OPERATIONS": "逻辑运算",
    "NOT CLARIFY": "进一步说明“非”",
    "NOT": "非",
    "OR VS AND": "“或”与“与”",
    "OR": "或",
    "PRIMITIVE BIGGER": "基础“大于”",
    "PRIMITIVE SMALLER": "基础“小于”",
    "THEREFORE": "所以",
    "TRUTH STATEMENT": "真值陈述",
    "PI": "圆周率",
    "ROUNDING INTRO": "舍入入门",
    "ROUNDING": "舍入",
    "3D SHAPES": "三维形状",
    "COUNT STRUCTURES": "结构计数",
    "NON-GEOMETRY STRUCTURE": "非几何结构",
    "STRUCTURE": "结构",
    "STRUCTURES SELF-CONTAIN": "结构自包含",
    "Data": "数据",
    "WHAT TYPE OF STRUCTURE": "哪种结构",
    "SPACE OBJECT QUIZ 4": "空间物体测验 4",
    "2 ATOMS BIGGER THAN 1": "两个原子比一个大",
    "ATOM 6": "原子 6",
    "ATOM VISUALIZED": "原子可视化",
    "ATOM": "原子",
    "Atoms": "原子",
    "ELEMENT GROUPS": "元素分组",
    "2 PLANET SYSTEM": "双行星系统",
    "ALIEN PLANET MASS": "外星行星质量",
    "ALIEN PLANET ORBITAL RADIUS": "外星行星轨道半径",
    "ALIENS PLANET BIGGER": "外星人的行星更大",
    "NAME ALIENS PLANET": "为外星人的行星命名",
    "NAME EARTH PLANET": "为地球命名",
    "VISUALIZE MOON": "月球可视化",
    "ATOMS MAKE EVERYTHING": "原子构成万物",
    "CHEMICAL ADDITION": "化学加法",
    "CHEMICAL EQUATION": "化学方程式",
    "CHEMREACT": "化学反应",
    "COMPOUND ADDITION": "化合物加法",
    "COMPOUNDS WITH DUPLICATES": "含重复成分的化合物",
    "Chemical Compounds": "化合物",
    "Elemental Properties": "元素性质",
    "HELIUM IS NOBLE": "氦是稀有气体",
    "MORE COMPLEX COMPOUNDS": "更复杂的化合物",
    "REACTION": "反应",
    "ROTATION": "旋转",
    "BLACKHOLE": "黑洞",
    "VISUALIZE BLACKHOLE": "黑洞可视化",
    "VISUALIZE WHITEDWARF": "白矮星可视化",
    "WHITEDWARF": "白矮星",
    "DESTROY DECAY": "衰变破坏",
    "DESTROY OPPOSITE": "破坏的反义",
    "Break Things": "破坏事物",
    "ALTERNATIVE DUMMY 1": "备选占位 1",
    "ALTERNATIVE DUMMY 3": "备选占位 3",
    "ALTERNATIVE YET YET AGAIN": "又一次备选",
    "Alternative": "备选",
    "DOER-DONETO CLARIFIED": "施事与受事说明",
    "MATH SENTENCE": "数学句子",
    "NOUN OPPOSITES": "名词反义词",
    "NOUN VERB OPPOSITES": "名词与动词的反义词",
    "NOUN VS VERB FINAL CHECK": "名词与动词最终检查",
    "OPPOSITE NUMBERS": "相反数",
    "Opposite": "相反",
    "Parts of Speech": "词性",
    "SHAPE SENTENCE": "形状句子",
    "ALIEN METALLICITY": "外星星系金属丰度",
    "DISTANCE FROM GALAXY CENTER": "距银河系中心的距离",
    "HOW TO FIND US": "如何找到我们",
    "How to Find Aliens": "如何找到外星人",
    "DISTANCE FOR DIMENSIONS": "各维度的距离",
    "LARGER TIME UNITS": "更大的时间单位",
    "METEOR MASS": "陨石质量",
    "METEOR SHAPE": "陨石形状",
    "METEOR TRAVEL TIME": "陨石飞行时间",
    "MOTION": "运动",
    "Motion": "运动",
    "MOTION BY DELTA": "用变化量表示运动",
    "2 ISOTOPES": "两种同位素",
    "ATOM MAKE TEST": "原子构成测试",
    "CLARIFY DECAY": "进一步说明衰变",
    "DIFFERENTIATE PROTONS AND ELECTRONS": "区分质子与电子",
    "HALF-LIFE": "半衰期",
    "ISOTOPES": "同位素",
    "SOLVE FOR NEUTRONS": "求中子数",
    "SUBATOMIC ATOM": "原子的亚原子结构",
    "SUBATOMIC VISUALS": "亚原子结构可视化",
    "VISUALIZE DECAY": "衰变可视化",
    "VISUALIZE SUBATOMIC": "亚原子结构可视化",
    "ALIEN STAR SIZE": "外星恒星大小",
    "ALPHA CAPTURE": "α 粒子俘获",
    "FUSION CREATES ELEMENTS": "核聚变生成元素",
    "Nuclear Fusion": "核聚变",
    "STAR COUNT": "恒星数量",
    "CALCULATE MOVE TIME": "计算移动时间",
    "DIFFERENT HALF LIVES": "不同的半衰期",
    "HELISEC": "HELISEC",
    "MESSAGE TIME": "讯息时间",
    "RATE": "速率",
    "SODIUM 25 HALF-LIFE": "钠-25 半衰期",
    "TIME": "时间",
    "VISUALIZE HE6 DECAY": "氦-6 衰变可视化",
    "HETER": "HETER",
    "LIGHTSPEED IS SIGNAL SPEED": "光速就是信号速度",
    "MFG": "MFG",
    "MINIHETER": "MINIHETER",
    "SPEED OF LIGHT": "光速",
    "UNIT REVIEW": "单位复习",
    "UNIT": "单位",
    "USE FILOGRAM": "使用 FILOGRAM",
    "WHO IS HEAVIER": "谁更重",
    "Abstract Equality": "抽象等价",
    "IS IS CONCRETE OR ABSTRACT": "“是”表示具体还是抽象",
    "IS": "是",
    "ABSTRACT & CONCRETE EXAMPLES": "抽象与具体示例",
    "ABSTRACT CONCRETE QUIZ 2": "抽象与具体测验 2",
    "Abstraction": "抽象",
    "CONCRETE CONTINUED ABSTRACT CONTINUED": "具体与抽象进阶",
    "ALMOST GEOMETRY SIZE": "近似几何尺寸",
    "ALMOST STRUCTURES": "近似结构",
    "ALMOST": "近似",
    "Approximation": "近似",
    "BIG STRUCTURE LITTLE STRUCTURE": "大结构与小结构",
    "RELATIVE ALMOST BIG": "相对近似“大”",
    "ALIEN LOCATION IS KNOWN": "外星人的位置已知",
    "EXPANDING UNIVERSE": "膨胀的宇宙",
    "FINITE UNIVERSE": "有限宇宙",
    "KNOWN UNKNOWN": "已知与未知",
    "PAST, PRESENT, FUTURE": "过去、现在与未来",
    "UNIVERSE GALAXY COUNT": "宇宙中的星系数量",
    "HYDROGEN SULFIDE CHEMOSYNTHESIS": "硫化氢化能合成",
    "LIFE DO BIOLOGICAL REACTIONS": "生命进行生物反应",
    "Life Reproduces": "生命繁殖",
    "LIFE REPRODUCES": "生命繁殖",
    "METHANOGENESIS": "产甲烷作用",
    "PARENTAGE": "亲子关系",
    "VISUALIZE DNA": "DNA 可视化",
    "ALIENS ARE HYCEAN": "外星人生活在海氢行星",
    "MULTIPLE CARBON IS STILL ORGANIC": "含多个碳原子仍属有机物",
    "ORGANIC COMPOUNDS BACKWARDS": "倒推有机化合物",
    "ADJECTIVE": "形容词",
    "LINKWORD": "连接词",
    "SIMPLE PARTS OF SPEECH TEST": "简单词性测试",
    "AFTER PUZZLE DUMMY": "“之后”占位谜题",
    "PREV PUZZLE DUMMY": "“之前”占位谜题",
    "PREVIOUS": "之前",
    "SEQUENTIAL THEN": "表示顺序的“然后”",
    "X AGO": "X 以前",
    "ALL GEOMETRY ISINGROUP STRUCTURE TOGETHER": "所有几何对象同属结构",
    "DOER ISINGROUP NOUN": "施事属于名词",
    "DONETO ISINGROUP NOUN": "受事属于名词",
    "GEOMETRY ISINGROUP STRUCTURE": "几何对象属于结构",
    "ISINGROUP": "属于组",
    "Some ? Group": "部分与未知分组",
    "MASS UNIT GROUP": "质量单位组",
    "SHAPE ISINGROUP NOT CIRCLE": "形状属于非圆形组",
    "Subgrouping": "子分组",
    "ALL OR NOTHING": "全部或全无",
    "ALL PLANETS BIGGER": "所有行星都更大",
    "ALL": "全部",
    "BIGGEST AND SMALLEST VOBJ": "最大与最小 VOBJ",
    "BIGGEST PLANET": "最大的行星",
    "Distribution Descriptors": "分布描述词",
    "MAJORITY MODE": "多数与众数",
    "MAJORITY": "多数",
    "MINORITY CLARIFY": "明确“少数”",
    "NONE": "无",
    "SMALL ALIEN STAR": "较小的外星恒星",
    "STAR AND PLANET": "恒星与行星",
    "SUM OF ALL PLANETS": "所有行星之和",
    "BEFORE THE UNIVERSE": "宇宙诞生之前",
    "HUMANS ALIENS SIMILARITY": "人类与外星人的相似之处",
    "HUMANS UNKNOWN": "未知的人类",
    "LIFE IN THE UNIVERSE": "宇宙中的生命",
    "MANY METEORS": "许多陨石",
    "MORE THAN 1 PLANET WITH LIFE CONFIRMED": "已确认不止一颗行星有生命",
    "ABSTRACT IS VERY ABSTRACT": "抽象非常抽象",
    "BIG EXAMPLE": "“大”的示例",
    "BIG SMALL": "大与小",
    "STAR IS BIG EXAMPLE": "恒星是“大”的示例",
    "VERY": "非常",
    "VISUALIZE OTHER ATOM": "其他原子可视化",
    "VISUALIZE PROPANE": "丙烷可视化",
    "Carbon Compound Visuals": "碳化合物可视化",
    "2 Lives in 1 ??": "一个生命中的两个个体？",
    "BRAINUNIT AND LIMBUNIT": "BRAINUNIT 与 LIMBUNIT",
    "CAN BE PARENT IS NOT PARENT": "能成为亲本并不等于已是亲本",
    "REPRODUCE MEANS ADULT": "能繁殖意味着已成年",
    "SYNCHRONIZED REPRODUCTION": "同步繁殖",
    "WE ARE 2 SPECIES": "我们是两个物种",
    "WHEN LIMB DIE, BRAIN DIE": "肢体死亡时大脑也会死亡",
    "DRAW BABY AUNIT": "绘制幼年 AUNIT",
    "DRAW OLD AUNIT": "绘制老年 AUNIT",
    "MAXIMUM": "最大值",
    "MINMAX CLARIFY": "进一步说明最小值与最大值",
    "PHASES OF LIFE": "生命阶段",
    "AUTHORGUY IN LOVE": "AUTHORGUY 坠入爱河",
    "CHILD DEATH IS VERY SAD": "孩子死亡令人无比悲伤",
    "EMOTION": "情感",
    "HUMAN DEATH IS SAD": "人类死亡令人悲伤",
    "HUMAN HOPE LIVE": "希望人类延续下去",
    "LOVE HUMANITY": "热爱人类",
    "LOVE MATES": "爱自己的伴侣",
    "AUNITS DIFFER IN SIZE": "AUNIT 大小各异",
    "DRAW AUNIT": "绘制 AUNIT",
    "DRAW DIFFERENT AUNITS": "绘制不同的 AUNIT",
    "HUMAN POPULATION UNKNOWN": "人类人口数量未知",
    "HUMAN UNIT": "人类个体",
    "INDIVIDUAL": "个体",
    "BIRTH": "出生",
    "DIE": "死亡",
    "Lifecycle": "生命周期",
    "SPECIES": "物种",
    "HELIMONTH EXPLAINED": "解释 HELIMONTH",
    "HELIYEAR": "HELIYEAR",
    "Longer Time Units": "更大的时间单位",
    "PLANET ROTATION HELIYEAR": "行星公转与 HELIYEAR",
    "TIME UNITS ORDERED": "时间单位排序",
    "AUTHOR IS DEAD": "作者已经去世",
    "HOPE WE LIVE ON": "希望我们延续下去",
    "Meteor Makers": "陨石制造者",
    "NAME THE TRANSLATOR": "说出翻译员的名字",
    "WE HOPE HUMANS LIVE TOO": "我们也希望人类活下去",
    "ALIEN GESTATION PERIOD": "外星人的妊娠期",
    "ALL ARE CHILD, SOME ARE PARENT": "都是子代，部分是亲本",
    "AUTHORGUY AGE": "AUTHORGUY 的年龄",
    "AVERAGE CHILD COUNT": "平均子代数",
    "DRAW MANY SIMPLE AUNITS": "绘制多个简单 AUNIT",
    "DRAW MULTIPLE CHILDREN": "绘制多个子代",
    "DRAW SIMPLE PARENTAGE": "绘制简单亲子关系",
    "MOST AUNIT ARE PARENTS": "大多数 AUNIT 都是亲本",
    "MOST LIFE ARE ASEXUAL": "大多数生命采用无性生殖",
    "Offspring": "后代",
    "WE ARE SEXUAL": "我们采用有性生殖",
    "GOOD AND BAD": "善与恶",
    "Simple Morality": "朴素道德",
    "9 BRAIN IS 1": "九个大脑合为一体",
    "BOTH HUMANS AND ALIENS HAVE BRAINS": "人类与外星人都有大脑",
    "BRAIN IS NOT UNIVERSAL": "大脑并非普遍存在",
    "Emotion Organ": "情感器官",
    "SMART ENOUGH TO MAKE METEOR": "智慧足以制造陨石",
    "16 INNER ELECTRICSENSORS": "16 个内部 ELECTRICSENSOR",
    "24 ELECTRICSENSORS": "24 个 ELECTRICSENSOR",
    "ELECTRICSENSOR": "ELECTRICSENSOR",
    "VISUALIZE ELECTRICSENSOR": "ELECTRICSENSOR 可视化",
    "ALL MASS ATTRACT": "所有质量都会相互吸引",
    "ATTRACT REPEL MAGNETICS": "磁力的吸引与排斥",
    "AUNIT INNER MUTUALISM": "AUNIT 内部互利共生",
    "ELECTRICITY": "电",
    "MUTUAL VICTORY LAP": "互利共生收官",
    "MUTUAL": "相互",
    "NEUTRONS ARE NEUTRAL": "中子呈电中性",
    "POSITIVE AND NEGATIVE": "正与负",
    "EVOLUTION": "演化",
    "Evolution": "演化",
    "NUMERICAL EVOLUTION": "数值演化",
    "SURVIVAL OF THE FITTEST": "适者生存",
    "ADVANCEMENT OF PREHISTORY": "史前时代的发展",
    "EVOLUTIONARY HISTORY 1": "演化史 1",
    "EVOLUTIONARY HISTORY 11": "演化史 11",
    "EVOLUTIONARY HISTORY 13": "演化史 13",
    "EVOLUTIONARY HISTORY 3": "演化史 3",
    "EVOLUTIONARY HISTORY 5": "演化史 5",
    "EVOLUTIONARY HISTORY 7": "演化史 7",
    "EVOLUTIONARY HISTORY 9": "演化史 9",
    "History of the Species": "物种演化史",
    "Sensory Organ": "感觉器官",
    "LIGHT": "光",
    "ORGAN": "器官",
    "VISUALIZE EYE": "眼睛可视化",
    "ALIENS STATE OF MATTER": "外星人的物态",
    "Heat": "热量",
    "STATE OF MATTER TEST 1": "物态测试 1",
    "STATE OF MATTER TEST 3": "物态测试 3",
    "TEMPERATURE": "温度",
    "VISUALIZE GAS": "气体可视化",
    "VISUALIZE LIQUID": "液体可视化",
    "WHAT IS HOTTER": "哪个更热",
    "COUNT INNER POINTS": "内部点计数",
    "INNER OUTER": "内部与外部",
    "Inside & Outside": "内部与外部",
    "HOPE FOR OTHER INTELLIGENCE": "期盼其他智慧生命",
    "INTELLIGENT": "有智慧",
    "ONE DAY LEARN OF HUMAN INTELLIGENCE": "有朝一日了解人类智慧",
    "DEVELOPMENT OF LANGUAGE": "语言的发展",
    "LANGUAGE": "语言",
    "SCIENCE FROM US TO YOU": "把我们的科学传给你们",
    "THE ONLY LANGUAGE SPEAKERS": "唯一的语言使用者",
    "WE COMMUNICATED OUR HOME": "我们传达了家园的信息",
    "LIFE BEGAN IN OCEAN": "生命起源于海洋",
    "OCEAN": "海洋",
    "OCEANS BOILED OFF": "海洋被蒸发殆尽",
    "PART WHOLE AUNIT": "AUNIT 的部分与整体",
    "PART WHOLE CLARIFY 2": "明确部分与整体 2",
    "Part & Whole": "部分与整体",
    "SAME PARTS IS SAME WHOLE": "部分相同则整体相同",
    "SUBPARTS": "子部分",
    "ATMOSPHERES ARE NOT UNIVERSAL": "大气并非普遍存在",
    "ATMOSPHERIC MAKEUP METHANE": "大气成分：甲烷",
    "PLANET ATMOSPHERE": "行星大气",
    "Planetary Structure": "行星结构",
    "OLD PLANET WAS HOTTER": "古代行星更加炎热",
    "Ancient": "远古",
    "CLOSE SIDE": "近侧",
    "Near & Far": "远与近",
    "FAR SIDE": "远侧",
    "VISUALIZE ABSTRACT SIDES": "抽象侧面可视化",
    "VISUALIZE CLOSE": "近侧可视化",
    "HOT SIDE COLD SIDE IS PERMANENT": "热侧与冷侧固定不变",
    "SIDE CLOSER TO STAR IS HOTTER": "靠近恒星的一侧更热",
    "TIDALLY LOCKED": "潮汐锁定",
    "ATMOSPHERE CHANGE": "大气变化",
    "CHANGE": "变化",
    "CURRENT ATMOSPHERE": "当前大气",
    "PLANET LIFE CHANGED ATMOSPHERE": "行星生命改变了大气",
    "PREHISTORIC ATMOSPHERE": "史前大气",
    "Transformation": "转化",
    "ANIMALS CAN CONSUME": "动物可以摄食",
    "FISH": "鱼",
    "FOOD CHAIN": "食物链",
    "PREDATOR AND PREY": "捕食者与猎物",
    "PREHISTORIC LIMB AND CORAL": "史前肢体生物与珊瑚",
    "Ecology": "生态学",
    "Alien Sizes & Shapes": "外星生物的大小与形态",
    "DIVERSE SIZE": "大小各异",
    "MIDDLEAGE AUNIT VERTIZ": "中年 AUNIT 的 VERTIZ",
    "OLD AUNIT MASS": "老年 AUNIT 的质量",
    "YOUNG AUNIT VERTIZ": "幼年 AUNIT 的 VERTIZ",
    "ATHLETICS": "运动能力",
    "CAN WALK BAD AT SWIMMING": "能行走但不擅长游泳",
    "ELECTRICSPEAK RUDE IN WATER": "在水中使用 ELECTRICSPEAK 很失礼",
    "INATHLETIC SWIMMING": "不擅运动者的游泳方式",
    "INTELLECTUALLY CAPABLE": "拥有智慧",
    "MOVING SPEEDS": "移动速度",
    "CAPABLE": "具备能力",
    "Capabilities": "能力",
    "ELECTRICSPEAK": "ELECTRICSPEAK",
    "EYE CANNOT MAKE LIGHT": "眼睛不能发光",
    "CIVILIZATION": "文明",
    "COMMUNCATION IS COOPERATIVE": "沟通需要合作",
    "COOPERATE": "合作",
    "Cooperation": "合作",
    "COREBELIEF 0": "核心信念 0",
    "COREBELIEF 2": "核心信念 2",
    "COREBELIEF 4": "核心信念 4",
    "Alien Morality": "外星道德观",
    "CULTURE OVERLAP": "文化共通之处",
    "Culture": "文化",
    "AUTHORGUY DEATHCRISIS STANCE": "AUTHORGUY 对死亡危机的态度",
    "AUTHORMATE DEATHCRISIS STANCE": "AUTHORMATE 对死亡危机的态度",
    "CONSCIOUSNESS FROM BRAIN": "意识源于大脑",
    "CORALDEATH IS TRAGIC": "珊瑚死亡是一场悲剧",
    "DEATH IS PAINUL": "死亡令人痛苦",
    "DEATH SUCKS": "死亡很糟糕",
    "DEATHCRISIS DURATION": "死亡危机持续时间",
    "DEATHCRISIS IS ASYNC LIFESPANS": "死亡危机源于寿命不同步",
    "Views on Death": "死亡观",
    "FEELPAIN OPPOSITE IS ENJOYED": "痛苦的反面是愉悦",
    "HATING IS BAD": "仇恨是坏事",
    "INNER HATE IS BAD": "内心的仇恨是坏事",
    "ETCHING": "刻痕",
    "Ripples We Cast": "我们留下的涟漪",
    "GENERATIONS": "世代",
    "IMMORTAL ETCHING": "不朽的刻痕",
    "MULTIGENERATIONAL": "跨越多个世代",
    "ART": "艺术",
    "COMPETE FACTS NOT BELIEFS": "比拼事实，而非信念",
    "COMPETE": "竞争",
    "EXCELLENCE": "卓越",
    "Individual Talent": "个体才能",
    "FIELDS OF ART": "艺术领域",
    "MAKE METEOR IS EXCELLENCE": "制造陨石体现卓越",
    "SPIRIT OF COMPETITION": "竞争精神",
    "WE LOVE EXCELLENCE": "我们热爱卓越",
    "BELIEF": "信念",
    "BELIEVE": "相信",
    "KNOWN AND UNKNOWN FACTS": "已知与未知事实",
    "AUTHORGUY TRAINED IN SCIENCE": "AUTHORGUY 受过科学训练",
    "INTERNAL DIVERSITY": "内部多样性",
    "Compartmentalization": "区隔化",
    "TRAIN LIMBS": "训练肢体",
    "VISUALIZE LIMBSPEC": "LIMBSPEC 可视化",
    "METEOR IS LEARNGOOD": "陨石有助于学习",
    "METEOR IS MORALLY GOOD": "陨石在道德上是善的",
    "COMMUNICATE BY ELECTRICSENSOR": "使用 ELECTRICSENSOR 交流",
    "ELECTRICSENSOR IN WATER": "水中的 ELECTRICSENSOR",
    "GESTURE": "姿态",
    "IDEOLOGY": "意识形态",
    "OLDBELIEF YOUNGBELIEF": "旧信念与新信念",
    "AUTHORGUY ROTSYMM STANCE": "AUTHORGUY 对 ROTSYMM 的态度",
    "AUTHORMATE ROTSYMM STANCE": "AUTHORMATE 对 ROTSYMM 的态度",
    "OLDBELIEF ROTSYMM WHY": "旧信念为何推崇 ROTSYMM",
    "Alien Ethics": "外星伦理观",
    "YOUNGBELIEF ROTSYMM WHY": "新信念为何反对 ROTSYMM",
    "APLANET NOT ROTSYMM": "外星行星并非 ROTSYMM",
    "AUNIT ROTSYMM": "AUNIT 呈 ROTSYMM",
    "CUBE ROTSYMM": "立方体的 ROTSYMM",
    "LIMBSPEC OPPOSITE OF ROTSYMM": "LIMBSPEC 与 ROTSYMM 相反",
    "NON ROTSYMM": "非 ROTSYMM",
    "ROTSYMM IS NO INNER DIVERSITY": "ROTSYMM 意味着内部无差异",
    "ROTSYMM": "ROTSYMM",
    "Radial Symmetry": "放射对称",
    "SPHERE ROTSYMM": "球体呈 ROTSYMM",
    "AUTHORGUY AND AUTHORMATE IS BEST FRIENDS": "AUTHORGUY 与 AUTHORMATE 是最好的朋友",
    "AUTHORGUY ENJOYS SCIENCE": "AUTHORGUY 热爱科学",
    "FRIEND": "朋友",
    "HUMANITY IS FRIEND": "人类是朋友",
    "Intelligent Communication": "智慧生命的沟通",
    "LIFE ENJOYS UNIVERSE": "生命享受宇宙万物",
    "MASS LIMITED BY SPEED OF LIGHT": "质量受光速限制",
    "SAD IS FRIEND DIE": "朋友离世令人悲伤",
    "SOCIALIZE": "社交",
    "TRANSLATOR AND AUTHORGUY FRIENDS": "翻译员与 AUTHORGUY 是朋友",
    "SOCIALIZE AUTHORGUY STANCE": "AUTHORGUY 对交流的态度",
    "SOCIALIZE BELIEFS": "交流彼此的信念",
    "SOCIALIZE IDEOLOGY": "交流彼此的意识形态",
    "TOPICS OF DISCUSSION": "讨论的话题",
    "INFORMATION": "信息",
    "LIMITING": "限制",
    "WE TEACH SCIENCE NOW": "如今轮到我们传授科学",
    "COMPUTER MAKE FREQUENCY": "计算机产生频率",
    "COMPUTER": "计算机",
    "ENERGY IS HEAT": "能量就是热量",
    "ENERGY": "能量",
    "MASS ENERGY EQUIVALENCE": "质能等价",
    "STAR DO NUCLEAR FUSION": "恒星进行核聚变",
    "Spatial Dimensions": "空间维度",
    "ATOMIC FUSION MACHINE IN METEOR": "陨石中的核聚变装置",
    "FUSIONMACHINE IS LIMITLESS ENERGY": "聚变装置提供近乎无限的能量",
    "IS MASTERY OF TIME POSSIBLE": "能否掌握时间",
    "LEVELS OF MASTERY": "掌握程度",
    "Frontiers 2": "前沿 2",
    "MASTER OF ATOMS": "掌握原子",
    "MASTERY OF CHEMISTRY": "掌握化学",
    "MASTERY OF COOPERATION": "掌握合作",
    "MASTERY OF ENERGY": "掌握能量",
    "MASTERY OF INFORMATION": "掌握信息",
    "MASTERY OF LANGUAGE": "掌握语言",
    "MASTERY OF SCIENTIFIC THINKING EXAMPLE": "掌握科学思维的示例",
    "MASTERY OF SELF EXAMPLE": "掌握自我的示例",
    "MASTERY OF SPACE EXAMPLE": "掌握空间的示例",
    "MASTERY OF TIME IS UNKNOWN": "能否掌握时间尚不可知",
    "MASTERY OF TIME": "掌握时间",
    "MASTERY IS ALL KNOWN": "掌握意味着完全了解",
    "DEFINING GOODBYE": "定义“再见”",
    "Hello": "你好",
    "NEXT IS FINAL MESSAGE": "下一则就是最终讯息",
    "Preparing for the End": "为终章做准备",
    "SAY GOODBYE TO DEPARTED LOVED ONES": "向离世的挚爱道别",
    "SAY HELLO TO BORN ONES": "向新生者问好",
    "THANK YOU AND GOODBYE": "谢谢，再见",
    "THANKYOU": "谢谢",
    "TOTAL WORD COUNT": "词语总数",
    "Thank You": "谢谢",
    "YOU MUST LOVE US": "你们一定会爱上我们",
    "BIGGER SPHERE": "更大的球体",
    "CIRCLE": "圆",
    "Circles & Spheres": "圆与球体",
    "SPHERE 3": "球体 3",
    "COLOR REQUIRED": "必须指定颜色",
    "METEOR SCREEN CALIBRATE HIGH": "陨石屏幕高强度校准",
    "METEOR SCREEN COLOR TEST 1": "陨石屏幕色彩测试 1",
    "METEOR SCREEN COLOR TEST 3": "陨石屏幕色彩测试 3",
    "METEOR SCREEN COLOR TEST 5": "陨石屏幕色彩测试 5",
    "COLOR": "颜色",
    "Place Spheres": "放置球体",
    "VOBJ PARAMETERS": "VOBJ 参数",
    "VOBJ": "VOBJ",
    "SELF PORTRAIT": "自画像",
    "Glimpse of an Alien": "外星生物初现",
    "CIRCLE DIMENSIONS": "圆的尺寸",
    "SPHERE DIMENSIONS": "球体的尺寸",
    "WIDTH HEIGHT RECTANGLE": "矩形的宽与高",
    "VISUAL TEST 2": "视觉测试 2",
    "VISUAL TEST 4": "视觉测试 4",
    "VISUAL TEST 6": "视觉测试 6",
    "VISUAL": "图像",
    "Actinium": "锕",
    "days": "天",
    "hours": "小时",
    "Arsenic": "砷",
    "seconds": "秒",
    "billion years": "十亿年",
    "million years": "百万年",
    "Beryllium": "铍",
    "Boron": "硼",
    "Cadmium": "镉",
    "Cerium": "铈",
    "Chlorine": "氯",
    "Cobalt": "钴",
    "Erbium": "铒",
    "Fluorine": "氟",
    "Francium": "钫",
    "Gallium": "镓",
    "Holmium": "钬",
    "Indium": "铟",
    "Iodine": "碘",
    "Iron": "铁",
    "Lanthanum": "镧",
    "Lithium": "锂",
    "Lutetium": "镥",
    "Magnesium": "镁",
    "Manganese": "锰",
    "Molybdenum": "钼",
    "Neodymium": "钕",
    "Nickel": "镍",
    "Nitrogen": "氮",
    "Osmium": "锇",
    "Phosphorus": "磷",
    "Polonium": "钋",
    "Potassium": "钾",
    "Promethium": "钷",
    "Protactinium": "镤",
    "thousand years": "千年",
    "Radon": "氡",
    "Rhenium": "铼",
    "Rubidium": "铷",
    "Scandium": "钪",
    "Silicon": "硅",
    "Sodium": "钠",
    "Strontium": "锶",
    "Sulfur": "硫",
    "Tantalum": "钽",
    "Tellurium": "碲",
    "Terbium": "铽",
    "Thulium": "铥",
    "Tin": "锡",
    "Uranium": "铀",
    "Vanadium": "钒",
    "Yttrium": "钇",
    "Zinc": "锌",
}


def main() -> None:
    items = json.loads(SOURCE.read_text(encoding="utf-8"))
    missing = sorted({item["source_text"] for item in items} - TRANSLATIONS.keys())
    extra = sorted(TRANSLATIONS.keys() - {item["source_text"] for item in items})
    if missing or extra:
        raise SystemExit(f"mapping mismatch: missing={missing!r}, extra={extra!r}")

    result = [
        {
            "text_index": item["text_index"],
            "translated_text": TRANSLATIONS[item["source_text"]],
        }
        for item in items
    ]
    OUTPUT.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    NEWTERMS.write_text(NEW_TERM_NOTES, encoding="utf-8")
    print(f"generated {len(result)} translations ({len(TRANSLATIONS)} unique sources)")


if __name__ == "__main__":
    main()
